---
# file: main-yum.yml
# The tasks for the Cobbler role

# -------------
# Prerequisites
# -------------

- name: unsupported package manager
  fail: msg='this playbook requries yum or apt only'
  when: ansible_pkg_mgr != 'yum'

# ---------------
# Package Sources
# ---------------

# yum
- name: configure epel yum repo
  template: src=epel.repo.j2
        dest=/etc/yum.repos.d/epel.repo
        owner=root group=root mode=0644

# ------------
# Dependencies
# ------------

# yum
- name: install dependencies
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - syslinux
    - dhcp
    - xinetd
    - tftp-server

# -------
# selinux
# -------
- name: set selinux to permissive
  selinux: policy=targeted state=permissive

# -----
# dhcpd
# -----
- name: configure dhcpd
  template: src=dhcpd.j2 dest=/etc/sysconfig/dhcpd

- name: enable dhcpd
  service: name=dhcpd state=stopped enabled=true

# ---------
# firewalld
# ---------
- name: check if firewalld is installed
  sudo: yes
  command: which firewalld
  register: firewalld
  changed_when: false
  ignore_errors: true

- name: check if firewalld service is running
  sudo: yes
  command: firewall-cmd --state
  register: firewalld_svc
  ignore_errors: true
  when: firewalld|success

- name: enable cobbler tftpd through firewalld
  sudo: yes
  firewalld: service=tftp permanent=true state=enabled
  notify: restart firewalld
  when: firewalld|success and firewalld_svc.stdout=='running'

- name: enable cobbler httpd through firewalld
  sudo: yes
  firewalld: service=http permanent=true state=enabled
  notify: restart firewalld
  when: firewalld|success and firewalld_svc.stdout=='running'

# -------
# Cobbler
# -------

- name: install cobbler
  yum: name=cobbler state=present

- name: start and enable httpd
  service: name=httpd state=started enabled=true

- name: configure xinetd rsync
  copy: src=rsync
        dest=/etc/xinetd.d/
        owner=root group=root mode=0644
  notify: restart xinetd

- name: start and enable xinetd
  service: name=xinetd state=started enabled=true

- name: configure cobbler
  template: src=settings.j2 dest=/etc/cobbler/settings
  notify:
    - restart cobblerd
    - sync cobbler

- name: start and enable cobblerd
  service: name=cobblerd state=started enabled=true

- name: get cobbler loaders
  command: cobbler get-loaders
  args:
    creates: /var/lib/cobbler/loaders/README
  notify:
    - restart cobblerd
    - sync cobbler

- name: update cobbler signatures
  command: cobbler signature update
  notify:
    - restart cobblerd
    - sync cobbler

- name: configure cobbler dhcp
  template: src=dhcp.template.j2 dest=/etc/cobbler/dhcp.template
  notify:
    - restart cobblerd
    - sync cobbler
